package com.example.Balayage.regles.statsRegles;

public class StatsRegle implements Comparable<StatsRegle>{

    private Long id;
    private int ruleNumber;
    private int triggerNumber;
    private int exceptionsTriggeredNumber;

    public StatsRegle(int ruleNumber, int triggerNumber, int exceptionsTriggeredNumber) {
        this.ruleNumber = ruleNumber;
        this.triggerNumber = triggerNumber;
        this.exceptionsTriggeredNumber = exceptionsTriggeredNumber;
        //TODO change this to autogenerated
        id=Long.valueOf(1);
    }

    @Override
    public int compareTo(StatsRegle statsRegle) {
        return -Integer.compare(this.triggerNumber, statsRegle.triggerNumber);
    }

    public int getRuleNumber() {
        return ruleNumber;
    }

    public void setRuleNumber(int id) {
        this.ruleNumber = ruleNumber;
    }

    public int getTriggerNumber() {
        return triggerNumber;
    }

    public void setTriggerNumber(int triggerNumber) {
        this.triggerNumber = triggerNumber;
    }

    public int getExceptionsTriggeredNumber() {
        return exceptionsTriggeredNumber;
    }

    public void setExceptionsTriggeredNumber(int exceptionsTriggeredNumber) {
        this.exceptionsTriggeredNumber = exceptionsTriggeredNumber;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
}
